### ISSUE TITLE
Doesn't match latest revision on the plugin directory

### ISSUE THREAD

**Issue by chrisvanpatten** [elazar/wp-spam-honeypot#1]
I want to `git clone` the plugin and make some edits for my own nefarious purposes, but the version in this repo doesn't match the one on the plugin directory.

Really, I point this out this rather selfishly, as I'm just too lazy to deal with `git svn` :)

**Comment by ott** [comment]
It seems the tag is missing and the `svn` branch is also behind the `master` branch.

**Comment by elazar** [comment]
Fixed. Both WP SVN and GitHub should have consistent 1.0.0 and 1.1.0 tags now.
