### ISSUE TITLE
Accessibility: Not suited for blind users

### ISSUE THREAD

**Issue by andreasbossard** [elazar/wp-spam-honeypot#2]
Problem: Only a textarea is added without a label. So when blind people with a screenreader use it, the screenreader will show them the textfield even though it's "display:none". Maybe they fill it out, because they don't know what it is used for.

Suggestion: Add a label like "If you are a human, do not fill in this field."

**Comment by ott** [comment]
It looks like this issue can be closed.

**Comment by elazar** [comment]
@ott Has it been fixed on master?
