### ISSUE TITLE
License information missing

### ISSUE THREAD

**Issue by ott** [elazar/wp-spam-honeypot#6]
The `spam-honeypot` plugin currently has no license information attached to it. The original author uploaded the source code and accepted patches, so I assume that the plugin is supposed to be Free Software. However, in the current form it is proprietary software from a legal persepective. WordPress itself is licensed under the GPL2+, so the license for the plugin has to be GPL compatible.

**Comment by elazar** [comment]
Added [`LICENSE.txt`](https://github.com/elazar/wp-spam-honeypot/blob/master/LICENSE.txt) for GPLv2 to git master / svn trunk.
